FROM golang:1.22rc2-bookworm

RUN mkdir -p /go/src/github.com/tendermint/tools/tm-monitor
WORKDIR /go/src/github.com/tendermint/tools/tm-monitor

COPY Makefile /go/src/github.com/tendermint/tools/tm-monitor/

RUN make tools

COPY . /go/src/github.com/tendermint/tools/tm-monitor

